
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Insert title here</title>
 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700&display=swap" rel="stylesheet" type="text/css">
</head>
<body>
	<div class="container">
	<div style="text-align: center;"><img style="width: 170px ; height: 150px" src="https://i.pinimg.com/originals/30/d5/e6/30d5e6fc8b2fab452555c9314d72be59.gif"/></div>
	<div>
	<p style="text-align: center; font-family: Montserrat, sans-serif; font-size: 20px ; font-weight: bold;">Cập nhật lại mật khẩu !</p>
	<p style="text-align: center; font-family: Montserrat, sans-serif; font-size: 15px">Xin chào ${user}, bạn đã yêu cầu đặt lại mật khẩu của bạn ! <br>
	Mật khẩu mới của bạn là
	</p>
	
	</div>
	<hr>
	<center>
        <div style="background-color: rgb(39, 39, 145); width: 100px; height: 40px;">
            <p style="text-align: center; font-family: Montserrat, sans-serif; font-size: 15px ; font-weight: bold; color: white ; padding-top: 10px;">${passmoi}</p>
            </div>
    </center>
	<hr>
	<div>
	<p style="text-align: center; font-family: Montserrat, sans-serif; font-size: 15px">Nếu bạn có bất kì câu hỏi nào, vui lòng liên hệ với chúng tôi <br> qua email <strong>linhnkph24164@fpt.edu.vn</strong> <br>48 Ngõ 99 Cầu Diễn, Từ Liêm, Hà Nội.</p>
	</div>
	<div><img style="width: 1000px" src="https://img.freepik.com/free-vector/thank-you-placard-concept-illustration_114360-13436.jpg?w=2000"></div>
	</div>
</body>
</html>